#ifndef HASHMAP_171_HASH_FUNCTION_CONFIG_H
#define HASHMAP_171_HASH_FUNCTION_CONFIG_H


#define HASH_FUNC_OPT_1_AUTOPRINT_ERR  1
#define HASH_FUNC_OPT_1_ARG_ERR_STREAM stderr


#if !defined(HASH_FUNC_OPT_1_AUTOPRINT_ERR) | !defined(HASH_FUNC_OPT_1_ARG_ERR_STREAM)
#error "HASH_FUNC_OPT_1_AUTOPRINT_ERR" and "HASH_FUNC_OPT_1_ARG_ERR_STREAM" macros must be defined!
#endif


#endif // HASHMAP_171_HASH_FUNCTION_CONFIG_H
