#ifndef HASHMAP_171_AVL_TREE_CONFIG_H
#define HASHMAP_171_AVL_TREE_CONFIG_H


#define AVL_TREE_OPT_1_AUTOPRINT_ERR  1
#define AVL_TREE_OPT_1_ARG_ERR_STREAM stderr


#if !defined(AVL_TREE_OPT_1_AUTOPRINT_ERR) | !defined(AVL_TREE_OPT_1_ARG_ERR_STREAM)
#error "AVL_TREE_OPT_1_AUTOPRINT_ERR" and "AVL_TREE_OPT_1_ARG_ERR_STREAM" macros must be defined!
#endif


#endif // HASHMAP_171_AVL_TREE_CONFIG_H
