#ifndef HASHMAP_171_MULTISET_CONFIG_H
#define HASHMAP_171_MULTISET_CONFIG_H


#define MULTISET_OPT_1_AUTOPRINT_ERR  1
#define MULTISET_OPT_1_ARG_ERR_STREAM stderr


#if !defined(MULTISET_OPT_1_AUTOPRINT_ERR) | !defined(MULTISET_OPT_1_ARG_ERR_STREAM)
#error "MULTISET_OPT_1_AUTOPRINT_ERR" and "MULTISET_OPT_1_ARG_ERR_STREAM" macros must be defined!
#endif


#endif // HASHMAP_171_MULTISET_CONFIG_H
