name: Run Tests && Run App

on:
  push:
    branches: [ master ]
    paths: [ 'src/**' ]
  pull_request:
    branches: [ master ]
    paths: [ 'src/**' ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Set up repository
        uses: actions/checkout@v2

      - name: Build
        run: |
          mkdir build && \
          cd build && \
          cmake .. && \
          make

      - name: Run Tests
        run: build/src/test/run_tests

      - name: Run App - MD5 - size = 1000
        run: build/src/main/run_app ../../../src/res/war_and_peace.txt 1000 md5

      - name: Run App Polynomial - size = 1000
        run: build/src/main/run_app ../../../src/res/war_and_peace.txt 1000 polynomial

      - name: Run App SHA-1 - size = 1000
        run: build/src/main/run_app ../../../src/res/war_and_peace.txt 1000 sha-1

      - name: Run App - MD5 - size = 10
        run: build/src/main/run_app ../../../src/res/war_and_peace.txt 10 md5

      - name: Run App Polynomial - size = 10
        run: build/src/main/run_app ../../../src/res/war_and_peace.txt 10 polynomial

      - name: Run App SHA-1 - size = 10
        run: build/src/main/run_app ../../../src/res/war_and_peace.txt 10 sha-1
