name: Run Tests && Run App

on:
  push:
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Set up repository
        uses: actions/checkout@v2

      - name: Build
        run: |
          mkdir build && \
          cd build && \
          cmake .. && \
          make

      - name: Run Tests
        run: src/test/run_tests

      - name: Run App
        run: src/main/run_app
