name: Run Tests && Run App

on:
  push:
    branches: [ master ]
    paths: [ 'src/**' ]
  pull_request:
    branches: [ master ]
    paths: [ 'src/**' ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Set up repository
        uses: actions/checkout@v2

      - name: Build
        run: |
          mkdir build && \
          cd build && \
          cmake .. && \
          make

      - name: Warm up machine
        run: for i in {1..10}; do build/src/main/run_app src/res/war_and_peace.txt 1000 polynomial; done

      - name: Run App - Polynomial - size = 1
        run: build/src/main/run_app src/res/war_and_peace.txt 1 polynomial

      - name: Run App - Polynomial - size = 10
        run: build/src/main/run_app src/res/war_and_peace.txt 10 polynomial

      - name: Run App - Polynomial - size = 100
        run: build/src/main/run_app src/res/war_and_peace.txt 100 polynomial

      - name: Run App - Polynomial - size = 1000
        run: build/src/main/run_app src/res/war_and_peace.txt 1000 polynomial

      - name: Run App - Polynomial - size = 10000
        run: build/src/main/run_app src/res/war_and_peace.txt 10000 polynomial

      - name: Run Tests
        run: build/src/test/run_tests
